name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NO: '05'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', env.NO)) }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm ci
        run: npm ci
        working-directory: ${{ env.NO }}
      - name: npm run build
        run: npm run build
        working-directory: ${{ env.NO }}
      - name: mkdir & cp
        run: |
          mkdir ${NO}_tmp
          cp -pr ${NO}/public/*.css ${NO}/public/*.html ${NO}_tmp
      - name: git config
        run: |
          git config --local user.email 'ntt-developers@googlegroups.com'
          git config --local user.name 'NTT Developers'
      - name: git fetch
        run: git fetch origin gh-pages
      - name: git checkout
        run: |
          git checkout gh-pages
          git checkout ${GITHUB_SHA} README.md
      - name: git add & git commit
        run: |
          rm -rf ${NO}
          mv ${NO}_tmp ${NO}
          git add README.md ${NO}
          git commit -a --amend -m 'Automatic build by GitHub Actions'
      - name: git push
        run: git push -f origin gh-pages:gh-pages
